global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi_app'
    static_configs:
      - targets: ['localhost:8000']   # FastAPI /metrics

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']   # System metrics


